/**
 * Textos de la sección Protection (window tint + ceramic coating) en EN y ES.
 * Módulo de datos puro: lo importan la home (React) y el generador de páginas estáticas.
 *
 * Reglas (BRAND.md): sin cifras de calor/UV/TSER, sin precios, sin "de por vida", sin "9H",
 * sin plazos ni garantías que el cliente no haya confirmado. Lo que falta se omite.
 * La parte legal resume F.S. 316.2951–316.2957 y requiere revisión de un abogado de Florida.
 */
export const protection = {
  en: {
    navProtection: 'Tint & Ceramic',
    protEyebrow: 'PROTECTION · WINDOW TINT + CERAMIC COATING',
    protTitle: 'Florida sun is relentless. Your car doesn’t have to take it.',
    protSub: 'Ceramic and carbon window tint, plus ceramic coating for your paint, installed to the same showroom standard as every detail we do. Free quote by photo.',
    protTabTint: 'Window Tint',
    protTabCeramic: 'Ceramic Coating',
    protGroupLabel: 'Choose a service',

    protB1T: 'Help keeping the cabin cooler',
    protB1D: 'Heat-rejecting film can help keep the cabin cooler and cut glare. Results depend on the film, your car and the sun. Ask for the manufacturer’s spec sheet.',
    protB2T: 'Added protection inside and out',
    protB2D: 'UV-blocking film helps reduce sun fading of dash, seats and trim. Ceramic coating helps paint resist sun, salt and water spots.',
    protB3T: 'Privacy, with Florida’s limits explained',
    protB3D: 'Before we cut a single piece, we tell you the legal minimum for each window of your car and recommend a film that fits it.',
    cerB1T: 'Easier washing',
    cerB1D: 'A slick surface helps dirt and water rinse off, so washing can take less effort.',
    cerB2T: 'Added paint protection',
    cerB2D: 'Ceramic coating helps paint resist sun, salt, bird droppings and water spots.',
    cerB3T: 'Prepared before it’s coated',
    cerB3D: 'We wash, decontaminate and polish the paint first, so the coating bonds to a clean surface.',

    tintH: 'Window tint: ceramic and carbon films',
    tintLead: 'Choose the film that fits how you drive. We help you pick, and we quote from photos of your car.',
    cmpTitle: 'Carbon or ceramic?',
    cmpHead1: 'Carbon film',
    cmpHead2: 'Ceramic film',
    cmpR1: 'Heat rejection', cmpR1a: 'Good', cmpR1b: 'Typically higher',
    cmpR2: 'Color stability', cmpR2a: 'Ask for the written warranty', cmpR2b: 'Ask for the written warranty',
    cmpR3: 'Look', cmpR3a: 'Deep, matte finish', cmpR3b: 'Neutral, high clarity',
    cmpR4: 'A good fit for', cmpR4a: 'Daily drivers and everyday value', cmpR4b: 'Greater comfort in Florida heat, typically',
    cmpNote: 'Exact heat and UV figures come from the manufacturer’s spec sheet for each film model. Ask for it with your quote.',
    cmpUse: 'Quote this film',

    protGuide: 'Read the full guide',
    legalLead: 'In Florida, tint on a passenger car must let at least 28% of visible light through the front side windows and at least 15% through the rear side and back windows. Multipurpose vehicles may go down to 6% behind the driver. The limit is measured on the finished window, glass plus film.',
    legalTblWin: 'Window', legalTblCar: 'Passenger car', legalTblMpv: 'Multipurpose vehicle*',
    legalRowFront: 'Front side windows', legalRowRear: 'Rear side windows', legalRowBack: 'Back window', legalRowWind: 'Windshield',
    legalWindCell: 'Transparent strip at the top, above the AS-1 line',
    legalTblNote: 'Minimum visible light that must pass through the finished window. *Built on a truck chassis or with off-road features; we confirm how your vehicle is classified.',
    legalSource: 'Statute text',
    legalChecked: 'Summary checked against the statutes on October 4, 2026. It is not legal advice.',
    faqQuoteCerQ: 'How do I get a ceramic coating quote?',
    faqQuoteCerA: 'Send photos of the hood, roof and sides in daylight, plus the paint color, on WhatsApp, or use the form. We reply with a price range and next steps. The final price is confirmed once we see your car.',
    faqTimeTintQ: 'How long does window tint take?',
    faqTimeTintA: 'It depends on the vehicle and the number of windows. Tint is usually a few hours. We confirm timing and aftercare in your quote.',
    faqTimeCerQ: 'How long does a ceramic coating job take?',
    faqTimeCerA: 'It depends on the vehicle and the condition of the paint. The work includes washing, decontamination, polishing and curing time, so it takes longer than a wash. We confirm timing and aftercare in your quote.',
    legalTitle: 'Is window tint legal in Florida?',
    legalP1: 'Florida limits how dark window tint can be (F.S. 316.2951–316.2957). The limit is measured on your car’s finished window, glass plus film. On passenger cars, front side windows must let in at least 28% of visible light, and rear side windows and the back window at least 15%. Vehicles the law classifies as multipurpose passenger vehicles (built on a truck chassis or with off-road features) may go down to 6% behind the driver. Reflectivity is capped too: 25% on front side windows and 35% behind the driver, so mirror-like film is not allowed. We confirm how your vehicle is classified before we recommend a film.',
    legalP2: 'The windshield may only have a transparent strip along the top, above the AS-1 line marked on the glass. The installer must place a label on the inside of the driver-side door jamb with the film’s trade name and the installer’s business name. Tint that is too dark can mean a traffic ticket for the driver and having to remove the film, and it reduces visibility at night.',
    legalP3: 'A vehicle with a Florida DHSMV sunscreening medical exemption certificate (F.S. 316.29545) may be darker. The certificate belongs to one vehicle and cannot be transferred. We install to the certificate you show us. We don’t give medical advice and we don’t file exemptions.',
    legalP4: 'This is a summary, not legal advice. Rules can change, so confirm current requirements with the state or your installer before you order.',

    ceramicH: 'Ceramic coating for your paint',
    ceramicLead: 'A ceramic coating bonds a hard, slick layer to your clear coat. It helps paint resist sun, salt, bird droppings and water spots, and it makes washing easier.',
    ceramicHonest: 'It does not make paint scratch-proof or stop rock chips, and the car still needs proper washing. How long it protects depends on the product and your maintenance, and we confirm both in your quote.',
    cerS1: 'Careful wash and decontamination',
    cerS2: 'Polish to the level your paint needs',
    cerS3: 'Coating applied and left to cure undisturbed',

    ctaWhatsapp: 'Get my quote by photo',
    ctaForm: 'Request a quote',
    ctaLegal: 'Florida tint rules',
    ctaPhotosTitle: 'What to send',
    ctaPhotosTint: 'Photos of the side and rear windows, any sunroof, and your current tint if you have one.',
    ctaPhotosCeramic: 'Photos of the hood, roof and sides in daylight, and the paint color.',
    ctaWhere: 'We confirm where and when the work is done in your quote.',

    waTint: 'Hi! I’d like a window tint quote. Car: ',
    waCeramic: 'Hi! I’d like a ceramic coating quote. Car: ',

    faqTintLegalQ: 'Is window tint legal in Florida?',
    faqTintLegalA: 'Yes, within limits. Florida sets a minimum amount of light that must pass through each window, measured on the finished glass, and allows only a transparent strip at the top of the windshield. We explain the limit for each window of your car before you book. Medical exemptions need a valid state certificate for that vehicle.',
    faqFilmQ: 'Ceramic or carbon window film?',
    faqFilmA: 'Carbon film is a popular everyday choice with a deep matte look. Ceramic film typically rejects more heat and stays very clear, which many Florida drivers prefer for a car that sits in the sun. Ask us for the spec sheet of the film we recommend.',
    faqTimeQ: 'How long does a tint or ceramic coating job take?',
    faqTimeA: 'It depends on the vehicle and the work. Tint is usually a few hours. Ceramic coating includes paint preparation and curing time, so it can take longer. We confirm timing and aftercare in your quote.',
    faqWarrantyQ: 'What does the warranty cover?',
    faqWarrantyA: 'Warranties come with the specific film or coating used, and the terms vary. Ask for the written terms for the exact product before you book.',
    faqScratchQ: 'Does ceramic coating make paint scratch-proof?',
    faqScratchA: 'No. It adds a hard, slick layer that helps resist UV, bird droppings and water spots, and makes washing easier. It does not stop rock chips or deep scratches.',
    faqQuoteQ: 'How do I get a quote?',
    faqQuoteA: 'Send photos on WhatsApp or use the form: your car, the windows you want tinted and any existing tint. We reply with a price range and next steps. The final price is confirmed once we see your car.',

    // Formulario
    formVehicleText: 'Year, make, model',
    formDetails: 'Add details for a faster quote (optional)',
    formCoverage: 'Windows',
    covSides: 'Side windows', covRear: 'Rear window', covStrip: 'Windshield strip', covSunroof: 'Sunroof', covFull: 'All side and rear windows',
    formFilm: 'Film',
    filmCarbon: 'Carbon', filmCeramic: 'Ceramic', filmUnsure: 'Recommend one',
    formOldTint: 'Existing tint to remove',
    formZip: 'ZIP code',
    formConsent: 'I agree that {brand} may text me, message me on WhatsApp and call me at the number above about my quote and appointment, including with an automated system. I understand I do not have to agree to this to get a quote or to buy anything. Message frequency varies. Message and data rates may apply. Reply STOP to opt out or HELP for help.',
    formPrivacyLink: 'Privacy policy',
    formMessagingLink: 'Messaging terms',
    formSending: 'Sending…',
    formErrTitle: 'We couldn’t send your request.',
    formErrBody: 'Your details are still here. Try again, or message us on WhatsApp or call.',
    formErrFields: 'Check the highlighted fields.',
    formRetry: 'Try again',
    successTitle: 'Request received!',
    successBody: 'We’ll text or call you with a price range and next steps. For the fastest quote, send us photos on WhatsApp.',
    successWhatsapp: 'Send photos on WhatsApp',
    successRef: 'Your reference',
    formAvailability: 'Appointments are subject to availability. We confirm yours by message.',

    consentTitle: 'Your privacy choices',
    consentBody: 'With your permission we use cookies and pixels to measure visits and ads. Your quote request works the same either way.',
    consentAccept: 'Accept',
    consentReject: 'Reject',
    consentMore: 'Privacy policy',
    footerPrivacy: 'Privacy',
    footerPrivacyChoices: 'Privacy choices',
    footerIg: 'Follow us for daily work',
  },
  es: {
    navProtection: 'Polarizado y Cerámico',
    protEyebrow: 'PROTECCIÓN · POLARIZADO (WINDOW TINT) + CERÁMICO',
    protTitle: 'El sol de Florida no perdona. Tu auto no tiene por qué sufrirlo.',
    protSub: 'Polarizado cerámico y de carbono para los vidrios, más recubrimiento cerámico para la pintura, con el mismo estándar de showroom de cada detallado nuestro. Cotización gratis por foto.',
    protTabTint: 'Polarizado',
    protTabCeramic: 'Cerámico',
    protGroupLabel: 'Elige un servicio',

    protB1T: 'Ayuda a mantener la cabina más fresca',
    protB1D: 'La película que rechaza calor puede ayudar a mantener la cabina más fresca y reducir el reflejo. Los resultados dependen de la película, tu auto y el sol. Pide la ficha técnica del fabricante.',
    protB2T: 'Protección adicional por dentro y por fuera',
    protB2D: 'La película con bloqueo UV ayuda a reducir el desvanecimiento por el sol del tablero, los asientos y los plásticos. El recubrimiento cerámico ayuda a que la pintura resista sol, sal y manchas de agua.',
    protB3T: 'Privacidad, con los límites de Florida explicados',
    protB3D: 'Antes de cortar una sola pieza te decimos el mínimo legal de cada ventana de tu auto y te recomendamos una película acorde.',
    cerB1T: 'Lavado más fácil',
    cerB1D: 'Una superficie lisa ayuda a que la suciedad y el agua se enjuaguen, y lavar puede costar menos esfuerzo.',
    cerB2T: 'Protección adicional para la pintura',
    cerB2D: 'El recubrimiento cerámico ayuda a que la pintura resista sol, sal, excremento de aves y manchas de agua.',
    cerB3T: 'Preparada antes de recubrir',
    cerB3D: 'Primero lavamos, descontaminamos y pulimos la pintura, para que el recubrimiento se adhiera a una superficie limpia.',

    tintH: 'Polarizado: películas cerámica y de carbono',
    tintLead: 'Elige la película que va con tu forma de manejar. Te ayudamos a escoger y cotizamos con fotos de tu auto.',
    cmpTitle: '¿Carbono o cerámica?',
    cmpHead1: 'Película de carbono',
    cmpHead2: 'Película cerámica',
    cmpR1: 'Rechazo de calor', cmpR1a: 'Bueno', cmpR1b: 'Normalmente mayor',
    cmpR2: 'Estabilidad del color', cmpR2a: 'Pide la garantía escrita', cmpR2b: 'Pide la garantía escrita',
    cmpR3: 'Aspecto', cmpR3a: 'Mate profundo', cmpR3b: 'Neutro, alta claridad',
    cmpR4: 'Ideal para', cmpR4a: 'Uso diario y buena relación calidad-precio', cmpR4b: 'Mayor confort con el calor de Florida, normalmente',
    cmpNote: 'Las cifras exactas de calor y UV vienen de la ficha técnica del fabricante de cada modelo de película. Pídela con tu cotización.',
    cmpUse: 'Cotizar esta película',

    protGuide: 'Lee la guía completa',
    legalLead: 'En Florida, el polarizado de un auto de pasajeros debe dejar pasar al menos 28% de la luz visible por los vidrios laterales delanteros y al menos 15% por los laterales traseros y el vidrio trasero. Los vehículos multipropósito pueden bajar a 6% detrás del conductor. El límite se mide en el vidrio terminado, vidrio más película.',
    legalTblWin: 'Vidrio', legalTblCar: 'Auto de pasajeros', legalTblMpv: 'Vehículo multipropósito*',
    legalRowFront: 'Laterales delanteros', legalRowRear: 'Laterales traseros', legalRowBack: 'Vidrio trasero', legalRowWind: 'Parabrisas',
    legalWindCell: 'Franja transparente en la parte superior, sobre la línea AS-1',
    legalTblNote: 'Luz visible mínima que debe pasar por el vidrio terminado. *Construido sobre chasis de camión o con rasgos para uso fuera de carretera; confirmamos cómo está clasificado tu vehículo.',
    legalSource: 'Texto del estatuto',
    legalChecked: 'Resumen cotejado con los estatutos el 4 de octubre de 2026. No es asesoría legal.',
    faqQuoteCerQ: '¿Cómo pido una cotización de recubrimiento cerámico?',
    faqQuoteCerA: 'Envía por WhatsApp fotos del capó, el techo y los laterales con luz de día y el color de la pintura, o usa el formulario. Te respondemos con un rango de precio y los próximos pasos. El precio final se confirma cuando vemos tu auto.',
    faqTimeTintQ: '¿Cuánto tarda un polarizado?',
    faqTimeTintA: 'Depende del vehículo y de la cantidad de vidrios. El polarizado suele tomar unas horas. En tu cotización confirmamos tiempos y cuidados posteriores.',
    faqTimeCerQ: '¿Cuánto tarda un recubrimiento cerámico?',
    faqTimeCerA: 'Depende del vehículo y del estado de la pintura. El trabajo incluye lavado, descontaminado, pulido y tiempo de curado, así que toma más que un lavado. En tu cotización confirmamos tiempos y cuidados posteriores.',
    legalTitle: '¿El polarizado es legal en Florida?',
    legalP1: 'Florida limita qué tan oscuro puede ser el polarizado (F.S. 316.2951–316.2957). El límite se mide en el vidrio ya terminado de tu auto, vidrio más película. En autos de pasajeros, los vidrios laterales delanteros deben dejar pasar al menos 28% de la luz visible, y los laterales traseros y el vidrio trasero al menos 15%. Los vehículos que la ley clasifica como multipropósito (construidos sobre chasis de camión o con rasgos para uso fuera de carretera) pueden bajar a 6% detrás del conductor. La reflectividad también tiene tope: 25% en los laterales delanteros y 35% detrás del conductor, por lo que la película tipo espejo no está permitida. Antes de recomendar una película confirmamos cómo está clasificado tu vehículo.',
    legalP2: 'En el parabrisas solo se permite una franja transparente en la parte superior, por encima de la línea AS-1 marcada en el vidrio. El instalador debe colocar en la jamba interior de la puerta del conductor una etiqueta con el nombre comercial de la película y el nombre del negocio instalador. Un polarizado demasiado oscuro puede significar una multa de tránsito para el conductor y tener que retirar la película, y reduce la visibilidad de noche.',
    legalP3: 'Un vehículo con certificado de exención médica de polarizado del Departamento de Seguridad Vial y Vehículos Motorizados de Florida (F.S. 316.29545) puede llevar un tono más oscuro. El certificado pertenece a un solo vehículo y no se transfiere. Instalamos según el certificado que nos muestres. No damos consejo médico ni tramitamos exenciones.',
    legalP4: 'Esto es un resumen, no asesoría legal. Las reglas pueden cambiar; confirma los requisitos vigentes con el estado o con tu instalador antes de ordenar.',

    ceramicH: 'Recubrimiento cerámico para tu pintura',
    ceramicLead: 'El recubrimiento cerámico adhiere una capa dura y lisa al barniz de tu auto. Ayuda a que la pintura resista sol, sal, excremento de aves y manchas de agua, y facilita el lavado.',
    ceramicHonest: 'No vuelve la pintura a prueba de rayones ni evita golpes de piedra, y el auto sigue necesitando un lavado correcto. Cuánto protege depende del producto y de tu mantenimiento, y confirmamos ambos en tu cotización.',
    cerS1: 'Lavado cuidadoso y descontaminado',
    cerS2: 'Pulido al nivel que tu pintura necesita',
    cerS3: 'Aplicación del recubrimiento y curado sin perturbarlo',

    ctaWhatsapp: 'Pide tu cotización por foto',
    ctaForm: 'Solicitar cotización',
    ctaLegal: 'Reglas de polarizado en Florida',
    ctaPhotosTitle: 'Qué enviar',
    ctaPhotosTint: 'Fotos de los vidrios laterales y trasero, el sunroof si hay, y tu polarizado actual si tienes.',
    ctaPhotosCeramic: 'Fotos del capó, el techo y los laterales con luz de día, y el color de la pintura.',
    ctaWhere: 'En tu cotización confirmamos dónde y cuándo se hace el trabajo.',

    waTint: '¡Hola! Quisiera una cotización de polarizado. Auto: ',
    waCeramic: '¡Hola! Quisiera una cotización de recubrimiento cerámico. Auto: ',

    faqTintLegalQ: '¿El polarizado es legal en Florida?',
    faqTintLegalA: 'Sí, dentro de límites. Florida fija una cantidad mínima de luz que debe pasar por cada ventana, medida en el vidrio ya terminado, y solo permite una franja transparente en la parte superior del parabrisas. Antes de reservar te explicamos el límite de cada ventana de tu auto. Las exenciones médicas requieren un certificado estatal vigente para ese vehículo.',
    faqFilmQ: '¿Película cerámica o de carbono?',
    faqFilmA: 'La de carbono es una opción diaria popular, con acabado mate profundo. La cerámica normalmente rechaza más calor y se mantiene muy clara, lo que muchos conductores de Florida prefieren para un auto que pasa el día al sol. Pídenos la ficha técnica de la película que recomendamos.',
    faqTimeQ: '¿Cuánto tarda un polarizado o un recubrimiento cerámico?',
    faqTimeA: 'Depende del vehículo y del trabajo. El polarizado suele tomar unas horas. El cerámico incluye preparación de la pintura y tiempo de curado, así que puede tardar más. En tu cotización confirmamos tiempos y cuidados posteriores.',
    faqWarrantyQ: '¿Qué cubre la garantía?',
    faqWarrantyA: 'Las garantías vienen con la película o el recubrimiento específico que se use, y los términos varían. Pide por escrito los términos del producto exacto antes de reservar.',
    faqScratchQ: '¿El cerámico hace la pintura a prueba de rayones?',
    faqScratchA: 'No. Añade una capa dura y lisa que ayuda a resistir UV, excremento de aves y manchas de agua, y facilita el lavado. No evita golpes de piedra ni rayones profundos.',
    faqQuoteQ: '¿Cómo pido una cotización?',
    faqQuoteA: 'Envía fotos por WhatsApp o usa el formulario: tu auto, los vidrios que quieres polarizar y el polarizado actual si hay. Te respondemos con un rango de precio y los próximos pasos. El precio final se confirma cuando vemos tu auto.',

    formVehicleText: 'Año, marca, modelo',
    formDetails: 'Agrega detalles para cotizar más rápido (opcional)',
    formCoverage: 'Vidrios',
    covSides: 'Laterales', covRear: 'Trasero', covStrip: 'Franja del parabrisas', covSunroof: 'Sunroof', covFull: 'Todos los laterales y el trasero',
    formFilm: 'Película',
    filmCarbon: 'Carbono', filmCeramic: 'Cerámica', filmUnsure: 'Recomiéndame una',
    formOldTint: 'Polarizado anterior por retirar',
    formZip: 'Código postal',
    formConsent: 'Acepto que {brand} me envíe mensajes de texto, me escriba por WhatsApp y me llame al número indicado sobre mi cotización y mi cita, incluso con un sistema automatizado. Entiendo que no tengo que aceptar esto para recibir una cotización ni para comprar nada. La frecuencia de los mensajes varía. Pueden aplicar tarifas de mensajes y datos. Responde STOP para dejar de recibirlos o HELP para ayuda.',
    formPrivacyLink: 'Política de privacidad',
    formMessagingLink: 'Términos de mensajería',
    formSending: 'Enviando…',
    formErrTitle: 'No pudimos enviar tu solicitud.',
    formErrBody: 'Tus datos siguen aquí. Inténtalo de nuevo, o escríbenos por WhatsApp o llámanos.',
    formErrFields: 'Revisa los campos marcados.',
    formRetry: 'Intentar de nuevo',
    successTitle: '¡Solicitud recibida!',
    successBody: 'Te escribiremos o llamaremos con un rango de precio y los próximos pasos. Para cotizar más rápido, envíanos fotos por WhatsApp.',
    successWhatsapp: 'Enviar fotos por WhatsApp',
    successRef: 'Tu referencia',
    formAvailability: 'Las citas están sujetas a disponibilidad. Confirmamos la tuya por mensaje.',

    consentTitle: 'Tus opciones de privacidad',
    consentBody: 'Con tu permiso usamos cookies y píxeles para medir visitas y anuncios. Tu solicitud de cotización funciona igual en ambos casos.',
    consentAccept: 'Aceptar',
    consentReject: 'Rechazar',
    consentMore: 'Política de privacidad',
    footerPrivacy: 'Privacidad',
    footerPrivacyChoices: 'Opciones de privacidad',
    footerIg: 'Síguenos para trabajos diarios',
  },
}
